name: eBank-workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.x']

    env:
      POSTGRES_HOST: ${{secrets.DB_HOST}}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: typescript action
        uses: actions/typescript-action@v1
      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - name: Clean install
        run: npm ci
      - name: Connect to postgresql
        run: npm run dev
      # - name: Build project
      #   run: npm run build --if-present
      # - name: Test project
      #   run: npm run build
